### ISSUE TITLE
5-1 19번 테스트 케이스 채점에 대해서 질문 있습니다.

### ISSUE THREAD

**Issue by iwill231** [Jhuni0123/pl-checker#11]
![image](https://user-images.githubusercontent.com/22539407/32950818-1b5d3462-cbeb-11e7-82d1-fcff3bb4628b.png)

5-1 번에 19번 테스트케이스가 틀리다고 나와서 -k를 붙여서 돌려보면 저렇게 뜨는데 저게 맞는 답으로 알고 있는데 왜 계속 ./check상에서는 틀리다고 뜰까요;;;

**Comment by Jhuni0123** [comment]
출력파일과 결과 캡쳐를 올려주실 수 있을까요

**Comment by iwill231** [comment]
아 제가 바보였습니다ㅠㅠ -k옵션을 잘못이해했네요ㅠㅠ

**Comment by Jhuni0123** [comment]
:)
